apiVersion: batch/v1
kind: CronJob
metadata:
  name: step-cd
spec:
  schedule: "*/2 * * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: step-cd
            image: xstck/zad2gitops
            imagePullPolicy: IfNotPresent
            command:
            - /bin/sh
            - -c
            - |
              /usr/bin/git config --global user.name "cronjob" &&
              /usr/bin/git config --global user.email "cronjob@job.pl" &&
              mkdir temp &&
              cd temp &&
              /usr/bin/git clone https://github.com/xStck/Config-repo.git &&
              sleep 10 &&
              cd Config-repo &&
              kubectl apply -f deployment.yaml &&
              kubectl apply -f service.yaml &&
              kubectl apply -f ingress.yaml
          restartPolicy: Never
          serviceAccountName: gitops
      backoffLimit: 1


